// apps/web/src/index.tsx
import { ReadingApplication, SharedRoutes } from '@bible/app/application';
import { Router } from '@solidjs/router';
import { render, Show } from '@solidjs/web';
import { Effect } from 'effect';
import { createSignal, onSettled } from 'solid-js';

import { getDatabaseWorker } from './workers/database-worker.js';
import { webCapabilities } from './platform-capabilities.js';
import { startWebProcedureHost, type ActiveWebProcedureHost } from './workers/procedure-client.js';
import '@bible/app/styles.css';

const failureMessage = (cause: unknown): string => {
  if (cause instanceof Error) return cause.message;
  return 'An unknown startup error prevented the library from opening.';
};

const WebApplication = () => {
  const [host, setHost] = createSignal<ActiveWebProcedureHost>();
  const [failure, setFailure] = createSignal<unknown>();

  onSettled(() => {
    let disposed = false;
    let activeHost: ActiveWebProcedureHost | undefined;
    const starting = startWebProcedureHost(getDatabaseWorker());

    void starting.then(
      (started) => {
        activeHost = started;
        if (disposed) {
          void started.dispose();
          return;
        }
        setHost(started);
      },
      (cause: unknown) => {
        if (!disposed) setFailure(() => cause);
      },
    );

    return () => {
      disposed = true;
      if (activeHost !== undefined) void activeHost.dispose();
    };
  });

  return (
    <Show
      when={host()}
      fallback={
        <main class="bible-bootstrap" aria-live="polite">
          <Show when={failure()} fallback={<p role="status">Preparing your library…</p>}>
            {(cause) => (
              <div role="alert">
                <strong>The library could not be opened.</strong>
                <p>{failureMessage(cause())}</p>
              </div>
            )}
          </Show>
        </main>
      }
    >
      {(current) => (
        <Router
          root={(props) => (
            <ReadingApplication procedures={current().procedures} capabilities={webCapabilities}>
              {props.children}
            </ReadingApplication>
          )}
        >
          <SharedRoutes />
        </Router>
      )}
    </Show>
  );
};

const root = (() => {
  const element = document.getElementById('root');
  if (element === null) return Effect.runSync(Effect.die('#root not found'));
  return element;
})();
render(() => <WebApplication />, root);

// apps/desktop/src/main.tsx
import { ApplicationBootstrap } from '@bible/app/application';
import { HashRouter } from '@solidjs/router';
import { render } from '@solidjs/web';
import { Effect } from 'effect';

import { startDesktopProcedureHost } from './procedure-client.js';
import { desktopCapabilities } from './platform-capabilities.js';
import '@bible/app/styles.css';

const root = (() => {
  const element = document.getElementById('root');
  if (element === null) return Effect.runSync(Effect.die('#root not found'));
  return element;
})();
render(
  () => (
    <ApplicationBootstrap
      router={HashRouter}
      start={startDesktopProcedureHost}
      capabilities={desktopCapabilities}
    />
  ),
  root,
);
